{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# QDTrack multiple object detection and tracking with BDD100K\n",
    "\n",
    "https://github.com/SysCV/qdtrack/blob/master/docs/GET_STARTED.md"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Location of labels to convert:\n",
    "\n",
    "/run/media/sam/Dataset/QDTrack/data/bdd/labels-original/det_20\n",
    "\n",
    "/run/media/sam/Dataset/QDTrack/data/bdd/labels-original/box_track_20\n",
    "\n",
    "Location to convert to:\n",
    "\n",
    "/run/media/sam/Dataset/QDTrack/data/bdd/labels/det_20\n",
    "\n",
    "/run/media/sam/Dataset/QDTrack/data/bdd/labels/box_track_20\n",
    "\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "In order to have the following conversion scripts run correctly amendments where made to the bdd100k toolkit within the conda environment.\n",
    "../anaconda3/envs/qdtrack2/lib/python3.7/site-packages/bdd100k-1.0.0-py3.7.egg/bdd100k/label/to_coco.py\n",
    "\n",
    "Within the file the key value pairs / label names within the bdd100k labels where different to those within the to_coco.py file\n",
    "\n",
    "on line 145 \n",
    "\n",
    "if frame[\"labels\"] need to be changed to frame.get(\"labels\", none)\n",
    "\n",
    "within the mot label convesion label names need to be matched to dataset \n",
    "\n",
    "Conversion code of original label to coco format det 20:\n",
    "\n",
    "python -m bdd100k.label.to_coco -m det -i /run/media/sam/Dataset/QDTrack/data/bdd/labels-original/det_20/det_train.json -o /run/media/sam/Dataset/QDTrack/data/bdd/labels/det_20/det_train_cocofmt.json\n",
    "\n",
    "python -m bdd100k.label.to_coco -m det -i /run/media/sam/Dataset/QDTrack/data/bdd/labels-original/det_20/det_val.json -o /run/media/sam/Dataset/QDTrack/data/bdd/labels/det_20/det_val_cocofmt.json\n",
    "\n",
    "\n",
    "BoxTrack 20:\n",
    "\n",
    "python -m bdd100k.label.to_coco -m track -i /run/media/sam/Dataset/QDTrack/data/bdd/labels-original/box_track_20/train -o /run/media/sam/Dataset/QDTrack/data/bdd/labels/box_track_20/box_track_train_cocofmt.json\n",
    "\n",
    "python -m bdd100k.label.to_coco -m track -i /run/media/sam/Dataset/QDTrack/data/bdd/labels-original/box_track_20/val -o /run/media/sam/Dataset/QDTrack/data/bdd/labels/box_track_20/box_track_val_cocofmt.json\n",
    "\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Running QDTrack \n",
    "\n",
    "As I have access to a singel GPU (Nvidia 3090) I will follow the script to train with a single GPU\n",
    "\n",
    "python tools/train.py ${CONFIG_FILE} [optional arguments]\n",
    "\n",
    "The config file selected will be bdd100k\n",
    "\n",
    "/run/media/sam/Dataset/QDTrack/configs/bdd100k/qdtrack-frcnn_r50_fpn_12e_bdd100k.py\n",
    "\n",
    "No optional arguments will be supplied on the first run.\n",
    "\n",
    "command being entered into terminal conda env:\n",
    "\n",
    "python tools/train.py /run/media/sam/Dataset/QDTrack/configs/bdd100k/qdtrack-frcnn_r50_fpn_12e_bdd100k.py\n",
    "\n",
    "error:\n",
    "\n",
    "Traceback (most recent call last):\n",
    "  File \"tools/train.py\", line 11, in <module>\n",
    "    from mmdet.apis import set_random_seed\n",
    "  File \"/home/sam/anaconda3/envs/qdtrack/lib/python3.7/site-packages/mmdet/__init__.py\", line 25, in <module>\n",
    "    f'MMCV=={mmcv.__version__} is used but incompatible. ' \\\n",
    "AssertionError: MMCV==1.4.3 is used but incompatible. Please install mmcv>=1.3.8, <=1.4.0.\n",
    "(qdtrack) [sam@sam QDTrack]$ pip install mmcv==1.3.8\n",
    "\n",
    "\n",
    "pip installmmcv==1.3.8\n",
    "\n",
    "Re run command\n",
    "\n",
    "Error:\n",
    "\n",
    "Traceback (most recent call last):\n",
    "  File \"tools/train.py\", line 11, in <module>\n",
    "    from mmdet.apis import set_random_seed\n",
    "  File \"/home/sam/anaconda3/envs/qdtrack/lib/python3.7/site-packages/mmdet/apis/__init__.py\", line 1, in <module>\n",
    "    from .inference import (async_inference_detector, inference_detector,\n",
    "  File \"/home/sam/anaconda3/envs/qdtrack/lib/python3.7/site-packages/mmdet/apis/inference.py\", line 6, in <module>\n",
    "    from mmcv.ops import RoIPool\n",
    "  File \"/home/sam/anaconda3/envs/qdtrack/lib/python3.7/site-packages/mmcv/ops/__init__.py\", line 1, in <module>\n",
    "    from .bbox import bbox_overlaps\n",
    "  File \"/home/sam/anaconda3/envs/qdtrack/lib/python3.7/site-packages/mmcv/ops/bbox.py\", line 3, in <module>\n",
    "    ext_module = ext_loader.load_ext('_ext', ['bbox_overlaps'])\n",
    "  File \"/home/sam/anaconda3/envs/qdtrack/lib/python3.7/site-packages/mmcv/utils/ext_loader.py\", line 12, in load_ext\n",
    "    ext = importlib.import_module('mmcv.' + name)\n",
    "  File \"/home/sam/anaconda3/envs/qdtrack/lib/python3.7/importlib/__init__.py\", line 127, in import_module\n",
    "    return _bootstrap._gcd_import(name[level:], package, level)\n",
    "ModuleNotFoundError: No module named 'mmcv._ext'\n",
    "\n",
    "Try and locate missing module\n",
    "\n",
    "Solutions discussed here: https://github.com/open-mmlab/mmdetection/issues/3271\n",
    "\n",
    "First will check pytorch is compatable with nvidia and cua version\n",
    "\n",
    "Nvidia: 495.46\n",
    "\n",
    "Cuda 11.5\n",
    "\n",
    "Pytorch 1.10.1\n",
    "\n",
    "According to forum post pytorch latest will not run with cuda 11.5 but cant find recent confirming source\n",
    "\n",
    "This forum from pytorch seems to indicate 1.10 will be compatible with 11.x https://discuss.pytorch.org/t/pytorch-with-cuda-11-compatibility/89254/26\n",
    "\n",
    "so I will move onto mmcv fix before concluding cuda version should be downgraded\n",
    "\n",
    "Uninstalled version of mmcv:\n",
    "\n",
    "pip uninstall mmcv mmcv-full\n",
    "\n",
    "\n",
    "Went to mmcv github cloned repo and opened termianl at repo\n",
    "\n",
    "Command entered to setup mmcv:\n",
    "\n",
    "MMCV_WITH_OPS=1 python3 -m pip install -e .\n",
    "\n",
    "installation takin 15 mins +\n",
    "\n",
    "Tried running qdtrack\n",
    "\n",
    "Error:\n",
    "\n",
    "Traceback (most recent call last):\n",
    "  File \"tools/train.py\", line 11, in <module>\n",
    "    from mmdet.apis import set_random_seed\n",
    "  File \"/home/sam/anaconda3/envs/qdtrack/lib/python3.7/site-packages/mmdet/__init__.py\", line 25, in <module>\n",
    "    f'MMCV=={mmcv.__version__} is used but incompatible. ' \\\n",
    "AssertionError: MMCV==1.4.4 is used but incompatible. Please install mmcv>=1.3.8, <=1.4.0.\n",
    "\n",
    "Having to uninstall mmcv and try with this line\n",
    "\n",
    "pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cu11.5/torch1.10.1/index.html\n",
    "\n",
    "Return:\n",
    "\n",
    "Looking in links: https://download.openmmlab.com/mmcv/dist/cu11.5/torch1.10.1/index.html\n",
    "Collecting mmcv-full\n",
    "  Downloading mmcv-full-1.4.4.tar.gz (420 kB)\n",
    "     |████████████████████████████████| 420 kB 2.1 MB/s \n",
    "Requirement already satisfied: addict in /home/sam/anaconda3/envs/qdtrack/lib/python3.7/site-packages (from mmcv-full) (2.4.0)\n",
    "Requirement already satisfied: numpy in /home/sam/anaconda3/envs/qdtrack/lib/python3.7/site-packages (from mmcv-full) (1.21.5)\n",
    "Requirement already satisfied: packaging in /home/sam/anaconda3/envs/qdtrack/lib/python3.7/site-packages (from mmcv-full) (21.3)\n",
    "Requirement already satisfied: Pillow in /home/sam/anaconda3/envs/qdtrack/lib/python3.7/site-packages (from mmcv-full) (9.0.0)\n",
    "Requirement already satisfied: pyyaml in /home/sam/anaconda3/envs/qdtrack/lib/python3.7/site-packages (from mmcv-full) (6.0)\n",
    "Requirement already satisfied: yapf in /home/sam/anaconda3/envs/qdtrack/lib/python3.7/site-packages (from mmcv-full) (0.32.0)\n",
    "Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /home/sam/anaconda3/envs/qdtrack/lib/python3.7/site-packages (from packaging->mmcv-full) (3.0.7)\n",
    "Building wheels for collected packages: mmcv-full\n",
    "  Building wheel for mmcv-full (setup.py) ... \\\n",
    "\n",
    "Set up takes 15 min +\n",
    "\n",
    "Completed but version it donwloads is 1.4.4 which is flaggin as incompatable\n",
    "\n",
    "Next fix is to install mmcv-full==1.3.8\n",
    "\n",
    "Error:\n",
    "\n",
    "Traceback (most recent call last):\n",
    "  File \"tools/train.py\", line 11, in <module>\n",
    "    from mmdet.apis import set_random_seed\n",
    "  File \"/home/sam/anaconda3/envs/qdtrack/lib/python3.7/site-packages/mmdet/apis/__init__.py\", line 1, in <module>\n",
    "    from .inference import (async_inference_detector, inference_detector,\n",
    "  File \"/home/sam/anaconda3/envs/qdtrack/lib/python3.7/site-packages/mmdet/apis/inference.py\", line 6, in <module>\n",
    "    from mmcv.ops import RoIPool\n",
    "  File \"/home/sam/anaconda3/envs/qdtrack/lib/python3.7/site-packages/mmcv/ops/__init__.py\", line 1, in <module>\n",
    "    from .bbox import bbox_overlaps\n",
    "  File \"/home/sam/anaconda3/envs/qdtrack/lib/python3.7/site-packages/mmcv/ops/bbox.py\", line 3, in <module>\n",
    "    ext_module = ext_loader.load_ext('_ext', ['bbox_overlaps'])\n",
    "  File \"/home/sam/anaconda3/envs/qdtrack/lib/python3.7/site-packages/mmcv/utils/ext_loader.py\", line 12, in load_ext\n",
    "    ext = importlib.import_module('mmcv.' + name)\n",
    "  File \"/home/sam/anaconda3/envs/qdtrack/lib/python3.7/importlib/__init__.py\", line 127, in import_module\n",
    "    return _bootstrap._gcd_import(name[level:], package, level)\n",
    "ImportError: /home/sam/anaconda3/envs/qdtrack/lib/python3.7/site-packages/mmcv/_ext.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZNSt15__exception_ptr13exception_ptr9_M_addrefEv\n",
    "\n",
    "Found potential issue being conda installing both pytorch cpu and gpu:\n",
    "\n",
    "https://github.com/pyg-team/pytorch_geometric/issues/999\n",
    "\n",
    "Shall continue investigation to run tomorrow\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "From issues board uninstalling pytorch and installing directly from pytorch ould be a fix\n",
    "\n",
    "conda uninstall pytorch\n",
    "\n",
    "Pytorch github: https://github.com/pytorch/pytorch#get-the-pytorch-source\n",
    "\n",
    "Following source download and installation instructions for linux\n",
    "\n",
    "git clone --recursive https://github.com/pytorch/pytorch\n",
    "cd pytorch\n",
    "# if you are updating an existing checkout\n",
    "git submodule sync\n",
    "git submodule update --init --recursive --jobs 0\n",
    "\n",
    "export CMAKE_PREFIX_PATH=${CONDA_PREFIX:-\"$(dirname $(which conda))/../\"}\n",
    "python setup.py install\n",
    "\n",
    "which conda = /home/sam/anaconda3/condabin/conda\n",
    "\n",
    "conda prefix? = /home/sam/anaconda3/envs/qdtrack/\n",
    "\n",
    "export CMAKE_PREFIX_PATH=/home/sam/anaconda3/envs/qdtrack/:-\"/home/sam/anaconda3/condabin/conda\"\n",
    "python setup.py install\n",
    "\n",
    "pip install cmake\n",
    "\n",
    "Ran commands \n",
    "\n",
    "Error:\n",
    "Traceback (most recent call last):\n",
    "  File \"tools/train.py\", line 8, in <module>\n",
    "    import torch\n",
    "  File \"/home/sam/anaconda3/envs/qdtrack/lib/python3.7/site-packages/torch/__init__.py\", line 199, in <module>\n",
    "    from torch._C import *  # noqa: F403\n",
    "ImportError: /home/sam/anaconda3/envs/qdtrack/lib/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /home/sam/anaconda3/envs/qdtrack/lib/python3.7/site-packages/torch/lib/libtorch_python.so)\n",
    "\n",
    "\n",
    "Attempting to find a solution to activating glibcxx but no luck\n",
    "\n",
    "https://stackoverflow.com/questions/65349875/where-can-i-find-glibcxx-3-4-29\n",
    "\n",
    "\n",
    "https://forum.manjaro.org/t/missing-glibcxx-3-4-29/72542/2"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Could not fix this so have moved onto another model\n",
    "\n",
    "Details in log notes jan/22 end"
   ]
  }
 ],
 "metadata": {
  "interpreter": {
   "hash": "a94dfc396d5255bb893407f4c9d676c05f04d6de5674684e68f2ddc62cb1cb65"
  },
  "kernelspec": {
   "display_name": "Python 3.7.11 64-bit ('qdtrack2': conda)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "name": "python",
   "version": "3.9.0"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
